import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashCursor from "./components/ui components/SplashCursor/SplashCursor";
import ScrollFloat from "./components/ui components/ScrollFloat/ScrollFloat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-bg-primary text-white bg-[url('/backgrounds/1.jpg')] bg-cover bg-fixed bg-center layoutContainer`}
      >
        {/* <ScrollFloat
          animationDuration={1}
          ease="back.inOut(2)"
          scrollStart="center bottom+=50%"
          scrollEnd="bottom bottom-=40%"
          stagger={0.03}
        > */}
        {children}
        {/* <SplashCursor /> */}
        {/* </ScrollFloat> */}
      </body>
    </html>
  );
}
