import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashCursor from "./components/ui components/SplashCursor/SplashCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-bg-primary text-white bg-[url('/backgrounds/1.jpg')] bg-cover bg-fixed bg-center`}
      >
        <div id="smooth-content">{children}</div>
        {/* <div id="smooth-wrapper">
        </div> */}
        <SplashCursor />
      </body>
    </html>
  );
}
